[project]
name = "pykimori"
version = "0.1.0"
description = "wrapper for shikimori api"
readme = "README.md"
authors = [
    { name = "TYUFUN", email = "219561606+TYUFUN@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
pykimori = "pykimori:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
